# Generated by Django 2.1.7 on 2019-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
