# Generated by Django 2.1.7 on 2019-04-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('depart', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='LEARN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'learn',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(default='a', max_length=20)),
                ('pwd', models.IntegerField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
