# Generated by Django 2.1.5 on 2019-04-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('address', models.CharField(max_length=100, verbose_name='住址')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者管理',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20, verbose_name='书名')),
                ('auther', models.ManyToManyField(to='bank.Auther', verbose_name='作者')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍管理',
                'db_table': 'Book',
            },
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': '银行', 'verbose_name_plural': '银行管理'},
        ),
        migrations.AlterModelOptions(
            name='cardinfo',
            options={'verbose_name': '卡号', 'verbose_name_plural': '卡号管理'},
        ),
    ]
