# Generated by Django 2.1.5 on 2019-04-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20190430_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
