# Generated by Django 2.1.5 on 2019-04-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20190430_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='用户地址')),
                ('phone', models.CharField(max_length=11, verbose_name='用户联系方式')),
            ],
            options={
                'verbose_name': '持卡人详细信息',
                'verbose_name_plural': '持卡人详细信息管理',
                'db_table': 'CardInfoDetail',
            },
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='user',
            field=models.CharField(default='杨松林', max_length=10, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cardinfodetail',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.CardInfo', verbose_name='卡号'),
        ),
    ]
