# Generated by Django 2.1.7 on 2019-04-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=30, verbose_name='接口名称')),
                ('apiurl', models.CharField(max_length=200, verbose_name='接口地址')),
                ('apiparam', models.CharField(max_length=800, verbose_name='请求参数')),
                ('apimethod', models.CharField(max_length=100, verbose_name='请求方法')),
                ('apiresult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('apistatus', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('depend_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.Apis')),
            ],
            options={
                'verbose_name': '简历流转接口',
                'verbose_name_plural': '接口管理',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('types_id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('email2', models.EmailField(default='yangsonglin@qq.com', max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4')),
                ('types', models.IntegerField(choices=[(0, '超级管理员'), (1, '管理员'), (2, '导师'), (3, '成员'), (4, '游客')], default=4, help_text='选择用户类型的编号', verbose_name='用户类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员管理',
            },
        ),
    ]
